### ISSUE TITLE
Web ui not accessible in raspiblitz through local lan. 

### ISSUE THREAD

**Issue by RemoRitzmann** [lightningequipment/circuitbreaker#36]
You say circuitbreaker can be configured through a web ui. We need to open http://127.0.0.1:9235 in a browser.

The lcoal IP of my raspiblitz is 192.168.0.2 
So when I try to open 192.168.0.2:9235 It does not load the web ui.

**Comment by joostjager** [comment]
Maybe Raspiblitz does not yet have the latest version of circuitbreaker with web ui included?

**Comment by RemoRitzmann** [comment]
How can I see the version?

**Comment by RemoRitzmann** [comment]
admin@192.168.1.2:/home/circuitbreaker/circuitbreaker(master) ₿ ls
LICENSE  README.md  circuitbreaker-example.yaml  config.go  go.mod  go.sum  lndclient.go  lndclient_mock.go  log.go  main.go  process.go  process_test.go

**Comment by RemoRitzmann** [comment]
admin@192.168.1.2:/home/circuitbreaker/circuitbreaker(master) ₿ circuitbreaker --help
bash: circuitbreaker: command not found

**Comment by RemoRitzmann** [comment]
![image](https://user-images.githubusercontent.com/8985954/211731150-d3ef7617-27c2-4752-8d3b-7ef847f8bcb1.png)
What is the password for circuitbreaker?

**Comment by RemoRitzmann** [comment]
crosspost here: https://github.com/rootzoll/raspiblitz/issues/3603

**Comment by RemoRitzmann** [comment]
sudo su - circuitbreaker
circuitbreaker -V
**0.11.1-beta.rc3**

**Comment by RemoRitzmann** [comment]
any hints on how to access web ui are appreciated.

**Comment by joostjager** [comment]
You have to run the latest master version of circuitbreaker in raspiblitz. I'd say this is a raspiblitz question.

If you want to access the web ui from another machine, you do need to enable listening on all interfaces by adding `--httplisten 0.0.0.0:9235` to the circuitbreaker cmd line.

**Comment by joostjager** [comment]
Version reporting fixed in v0.4.0

**Comment by RemoRitzmann** [comment]
circuitbreaker@raspberrypi:~ $ circuitbreaker --httplisten 0.0.0.0:9235
Incorrect Usage. flag provided but not defined: -httplisten

**Comment by joostjager** [comment]
Closing this as it seems there is nothing to do in this repository.
