### ISSUE TITLE
service shows error after installing

### ISSUE THREAD

**Issue by RemoRitzmann** [lightningequipment/circuitbreaker#39]
![image](https://user-images.githubusercontent.com/8985954/213859363-e3fbc75e-8990-4785-936f-60de558a0d6d.png)

ERROR        Unexpected exit        {"err": "rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
Jan 21 08:40:34 raspberrypi circuitbreaker[3101427]: main.main
Jan 21 08:40:34 raspberrypi circuitbreaker[3101427]:         /home/circuitbreaker/circuitbreaker/main.go:143
Jan 21 08:40:34 raspberrypi circuitbreaker[3101427]: runtime.main
Jan 21 08:40:34 raspberrypi circuitbreaker[3101427]:         /usr/local/go/src/runtime/proc.go:255
Jan 21 08:40:34 raspberrypi systemd[1]: circuitbreaker.service: Succeeded.
Jan 21 08:41:34 raspberrypi systemd[1]: circuitbreaker.service: Scheduled restart job, restart counter is at 1.
Jan 21 08:41:34 raspberrypi systemd[1]: Stopped circuitbreaker Service.
Jan 21 08:41:34 raspberrypi systemd[1]: Started circuitbreaker Service.

**Comment by joostjager** [comment]
As with #36, you are not running the latest circuit breaker version (0.4.0).
