### ISSUE TITLE
Feature Request: Submit to Umbrel AppStore

### ISSUE THREAD

**Issue by aphex3k** [lightningequipment/circuitbreaker#42]
I would like to see the project added to the [Umbrel AppStore](https://github.com/getumbrel/umbrel-apps) eventually :) 

Let me know if you need a hand with this.

**Comment by joostjager** [comment]
Any help is more than welcome! I am not familiar with Umbrel.

**Comment by aphex3k** [comment]
If you can provide a resources for 
- 256x256 SVG icon
_(Submit an icon with no rounded corners as it will be dynamically rounded with CSS. GitHub doesn't allow uploading SVGs directly, so please upload your icon to an alternate service, like https://svgur.com, and paste the link below.)_

- Gallery images
_(Upload 3 to 5 high-quality gallery images (1440x900px) of your app in PNG format, or just upload 3 to 5 screenshots of your app and we'll help you design the gallery images.)_

I can get the whole thing started.

**Comment by joostjager** [comment]
Will see if I can get an image!

Just wondering what's the reason that you need a fork of mine for this? Can't you fork `umbrel-apps` and just do a PR on the upstream there?

**Comment by aphex3k** [comment]
> Just wondering what's the reason that you need a fork of mine for this? Can't you fork `umbrel-apps` and just do a PR on the upstream there?

I can, but the umbrel team encourages for the first creation of the app for the PR to come from the original developer account on github if possible.

**Comment by joostjager** [comment]
Got it. Created repo and added you!

**Comment by joostjager** [comment]
Done. Thanks again @aphex3k!
