### ISSUE TITLE
Something went wrong with my installation from Circuitbreaker on my Raspibolt

### ISSUE THREAD

**Issue by n-e-t-d-i-v-e-r** [lightningequipment/circuitbreaker#7]
Hi there
triede yesterday to install Circuitbreaker on my Raspibolt. As you can see here, installation seems to be OK:

`total 120
drwxr-xr-x 3 circuitbreaker circuitbreaker  4096 Apr 17 19:26 .
drwxr-xr-x 7 circuitbreaker circuitbreaker  4096 Apr 17 19:47 ..
drwxr-xr-x 8 circuitbreaker circuitbreaker  4096 Apr 17 19:26 .git
-rw-r--r-- 1 circuitbreaker circuitbreaker    14 Apr 17 19:26 .gitignore
-rw-r--r-- 1 circuitbreaker circuitbreaker  1068 Apr 17 19:26 LICENSE
-rw-r--r-- 1 circuitbreaker circuitbreaker  4943 Apr 17 19:26 README.md
-rw-r--r-- 1 circuitbreaker circuitbreaker  2332 Apr 17 19:26 circuitbreaker-example.yaml
-rw-r--r-- 1 circuitbreaker circuitbreaker  3208 Apr 17 19:26 config.go
-rw-r--r-- 1 circuitbreaker circuitbreaker   524 Apr 17 19:26 go.mod
-rw-r--r-- 1 circuitbreaker circuitbreaker 41395 Apr 17 19:26 go.sum
-rw-r--r-- 1 circuitbreaker circuitbreaker  3941 Apr 17 19:26 lndclient.go
-rw-r--r-- 1 circuitbreaker circuitbreaker  2312 Apr 17 19:26 lndclient_mock.go
-rw-r--r-- 1 circuitbreaker circuitbreaker   315 Apr 17 19:26 log.go
-rw-r--r-- 1 circuitbreaker circuitbreaker  4605 Apr 17 19:26 main.go
-rw-r--r-- 1 circuitbreaker circuitbreaker  9190 Apr 17 19:26 process.go
-rw-r--r-- 1 circuitbreaker circuitbreaker  2296 Apr 17 19:26 process_test.go
`

but if I will verify the version, i’ll get this:
`circuitbreaker@crownero:~ $ circuitbreaker --version
bash: circuitbreaker: command not found
`
and I also can’t start up the programm:
`admin@crownero:/usr/local/bin $ sudo systemctl start circuitbreaker
Failed to start circuitbreaker.service: Unit circuitbreaker.service not found.`

Maybe you can help me where I lost the right path during the configuration.

Thx for your support in advance

**Comment by n-e-t-d-i-v-e-r** [comment]
maybe this is also an important message:
`-bash: circuitbreaker: command not found`

**Comment by n-e-t-d-i-v-e-r** [comment]
at least something with the installation was going wrong?
`go: downloading github.com/decred/dcrd/lru v1.0.0
# runtime/internal/sys
/usr/local/go/src/runtime/internal/sys/stubs.go:9:7: PtrSize redeclared in this block
	/usr/local/go/src/runtime/internal/sys/arch.go:24:38: previous declaration
/usr/local/go/src/runtime/internal/sys/stubs.go:10:24: undefined: Uintreg`

**Comment by kristapsk** [comment]
@n-e-t-d-i-v-e-r What was your solution? I'm having similar issue trying to test / review https://github.com/raspibolt/raspibolt/pull/1374.

**Comment by n-e-t-d-i-v-e-r** [comment]
> @n-e-t-d-i-v-e-r What was your solution? I'm having similar issue trying to test / review [raspibolt/raspibolt#1374](https://github.com/raspibolt/raspibolt/pull/1374).

unfortunately I closed this issue unsolved, cause no one could help
