### ISSUE TITLE
Manual installation - unable to configure max HTLCs

### ISSUE THREAD

**Issue by Ripley81** [lightningequipment/circuitbreaker#71]
I'm running a manual installation of CB on a Raspibolt, which has a slightly outdated installation guide that refers to the config file as 'circuitbreaker.yaml'. However from what I am reading for the latest version, the config now sits within the db. I don't have the GUI installed as I am not running Docker.

How do I access the config to adjust the maxPendingHtlcs? 

Backdrop: I am getting "TEMPORARY_CHANNEL_FAILURE INSUFFICIENT_BALANCE insufficient bandwidth to route htlc" for a certain channel even though I have 4x the available balance and the max HTLCs set > than the attempted routing amount and still getting that error.

Further, it would be great to see a manual, non-Docker installation guide for the GUI.

Thanks!

**Comment by nclgvnzz** [comment]
@Ripley81 I was using the Raspibolt guide as a reference too and, just like you, I realized it was outdated so followed the instructions under "[Run locally](https://github.com/lightningequipment/circuitbreaker#run-locally)". You can change the maxPendingHtlcs only via the web user interface.

**Comment by joostjager** [comment]
That's correct indeed, with the latest version you can only configure through the web interface.

Docker is no longer required after the merge of #73 into master.

**Comment by Ripley81** [comment]
I appreciate the hint, but the Run locally instruction requires Docker.

"Build the frontend via docker: ./build_frontend.sh"

------- Original Message -------

**Comment by joostjager** [comment]
Readme updated
